#### general settings
name: FastSRx4_adv_DIV2K
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [0]
# resume_latest: true

attack:
  eps: 0.01569
  raw_data: true
adv_train:
  m: 4
  step: 0.01

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ../../data/DIV2K/train/HR/x4
    dataroot_LQ: ../../data/DIV2K/train/LR/x4

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set14
    mode: LQGT
    dataroot_GT: ../../data/Set14/HR/x4
    dataroot_LQ: ../../data/Set14/LR/x4

#### network structures
network_G:
  which_model_G: FastNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/FastSRx4_adv_DIV2K_pretrained_v0.1.pth
  strict_load: true
  resume_state: ~ 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  lr_steps: [100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000]
  lr_gamma: 0.5

  # lr_G: !!float 2e-4
  # lr_scheme: CosineAnnealingLR_Restart
  # beta1: 0.9
  # beta2: 0.99
  # niter: 1000000
  # warmup_iter: -1  # no warm up
  # T_period: [250000, 250000, 250000, 250000]
  # restarts: [250000, 500000, 750000]
  # restart_weights: [1, 1, 1]
  # eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
